config/routes.rb
Rails.application.routes.draw do

  resources :phone_numbers, only: [:new, :create]
  post 'phone_numbers/verify' => "phone_numbers#verify"

end

app/models/phone_number.rb
class PhoneNumber < ActiveRecord::Base
#	validates :phone_number, presence: true
	def generate_pin
		self.pin = rand(000000..999999).to_s.rjust(6, "0")
		self.save
	end

	def send_pin
		twilio_client.messages.create(
    		to: phone_number,
    		from: '+12014398966',
    		body: "Your PIN is #{pin}"
  		)
	end

	def verify(entered_pin)
  		update(verified: true) if self.pin == entered_pin
	end

	def twilio_client
  		Twilio::REST::Client.new("ACcb1b88114e0937d43e5e9e5ea65da8d1", "a56b38f4c7e005057fb24418818efade")
	end
end

#export TWILIO_ACCOUNT_SID="ACcb1b88114e0937d43e5e9e5ea65da8d1"
#export TWILIO_AUTH_TOKEN="a56b38f4c7e005057fb24418818efade"
#export TWILIO_PHONE_NUMBER="(201) 439-8966/+12014398966"

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController
	def new
		@phone_number = PhoneNumber.new
	end

	def create
		@phone_number = PhoneNumber.find_or_create_by(phone_number: params[:phone_number][:phone_number])
		@phone_number = params[:phone_number][:phone_number_area] + @phone_number
		@phone_number.generate_pin
		@phone_number.send_pin
		respond_to do |format|
			format.js
		end
	end

	def verify
  		@phone_number = PhoneNumber.find_by(phone_number: params[:hidden_phone_number])
  		@phone_number.verify(params[:pin])
  		respond_to do |format|
    		format.js
  		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phone_numbers_helper.rb
module PhoneNumbersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SMSVerification</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/phone_numbers/create.js.erb
$('#hidden_phone_number').val('<%= @phone_number.phone_number %>' )
$('#send-pin').hide()
$('#verify-pin').fadeToggle()
$('#pin').focus()

app/views/phone_numbers/new.html.erb
<div id="send-pin">
  <h3>What's your phone number?</h3>
  <%= form_for @phone_number, remote: true do |f| %>

    <div class="form-group">
    	<div class= "col-md-1">
    		<%= f.select(:phone_number_area, [['Area', "" ], ['China', "+86" ]]) %>
    	</div>
    	<div class= "col-md-2">
      		<%= f.text_field :phone_number, placeholder: "Phone Number" %>
      	</div>
    </div>
    <%= f.submit "Send PIN", class: "btn btn-primary", id: 'send-pin-link' %>
  <% end %>
</div>

<div id="verify-pin">
<h3>Enter your PIN</h3>
<%= form_tag phone_numbers_verify_path, remote: true do |f| %>
  <%= hidden_field_tag 'hidden_phone_number', '' %>
  <div class="form-group">
    <%= text_field_tag :pin %>
  </div>
  <%= submit_tag "Verify PIN", class: "btn btn-primary" %>
  <% end %>
</div>
 
<div id="status-box" class="alert alert-success">
  <p id="status-message">Status: Haven’t done anything yet</p>
</div>

app/views/phone_numbers/verify.js.erb
<% if @phone_number.verified %>
  $('#verify-pin').hide()
  $('#status-box').removeClass()
  $('#status-box').addClass('alert alert-success')
  $('#status-message').text('Success!!')
<% else %>
  $('#status-box').removeClass()
  $('#status-box').addClass('alert alert-warning')
  $('#status-message').text("Sorry, that wasn't the right pin.")
<% end %>
$('#status-box').fadeToggle()